name: counter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2 # For storing JWT token
  http: ^1.1.0 # For API calls
  country_flags: ^3.2.0
  lucide_icons: ^0.257.0
  video_player: ^2.7.2
  chewie: ^1.7.4
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
